'use client';
import React from 'react'
import styles from '@/styles/index';

// https://www.creative-tim.com/learning-lab/tailwind-starter-kit/documentation/react/modals/regular

function Navbar() {
  const [showModal, setShowModal] = React.useState(false);
  return (
    <nav className="sm:px-16 px-6 py-8 relative">
      <div className="absolute w-[50%] inset-0 gradient-01"/>
      <div className="inline">
        <div className="float-right">
          {/* <button className="bg-[#a45ee5] hover:bg-[#6d12c2] text-white font-bold py-2 px-4 rounded-full" >
            About
          </button> */}
          <button
            className="bg-[#a45ee5] hover:bg-[#6d12c2] text-white font-bold py-2 px-4 rounded-full"
            type="button"
            onClick={() => setShowModal(true)}
          >
            About
          </button>
        </div>
      </div>
      {showModal ? (
        <>
          <div
            className="backdrop-blur justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none"
          >
            <div className="relative w-auto my-6 mx-auto max-w-sm">
              {/*content*/}
              <div className="border-0 rounded-xl shadow-lg relative flex flex-col w-full bg-black outline-none focus:outline-none">
                {/*header*/}
                <div className="flex items-start justify-between px-5 pt-5">
                  <h3 className="text-2xl font-semibold text-white">
                    About
                  </h3>
                  <button
                    className="p-1 ml-auto bg-transparent border-0 text-black opacity-5 float-right text-3xl leading-none font-semibold outline-none focus:outline-none"
                    onClick={() => setShowModal(false)}
                  >
                    <span className="bg-transparent text-white opacity-5 h-6 w-6 text-2xl block outline-none focus:outline-none">
                      ×
                    </span>
                  </button>
                </div>
                {/*body*/}
                <div className="relative px-6 flex-auto">
                  <p className="my-4 text-slate-500 text-lg leading-relaxed">
                    Motivational GPT is a website powered by <a className="underline" href="https://chatgpt.com">Chat GPT</a> that generates motivational quotes. The quotes are generated by a neural network trained on a large dataset of motivational quotes. The neural network is trained using the <a className="underline" href="https://huggingface.co/gpt3">GPT-3</a> model.
                  </p>
                  <p className="my-4 text-slate-500 text-lg leading-relaxed">
                    This about section was written with the help of GitHub Copilot. 
                  </p>
                </div>
                {/*footer*/}
                <div className="flex items-center justify-end px-6 pb-6">
                  <button
                    className="text-red-500 background-transparent font-bold uppercase px-6 py-2 text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                    type="button"
                    onClick={() => setShowModal(false)}
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
        </>
      ) : null}
    </nav>
  );
}

export default Navbar;

// const Hi = () => (
//   <nav className="sm:px-16 px-6 py-8 relative">
//     <div className="absolute w-[50%] inset-0 gradient-01"/>
//     {/* <div className={`${styles.innerWidth} mx-auto align-middle justify-center flex`}>
//         <h2 className="font-extrabold text-[24px] leading-[30px] text-white">Motivational Quotes</h2>
//     </div>
//     <div className={`${styles.innerWidth} mx-auto align-middle justify-center flex`}>
//         <h3 className="font-semibold text-[16px] leading-[20px] text-white">Generated by Chat GPT</h3>
//     </div> */}
//     <div className="inline">
//       <div className="float-right">
//         <button className="bg-[#a45ee5] hover:bg-[#6d12c2] text-white font-bold py-2 px-4 rounded-full">
//           About
//         </button>
//       </div>
//     </div>
//   </nav>
// );